# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/abdul_waheed/Music/rv32_for_fyp/project_1/project_1.cache/wt [current_project]
set_property parent.project_path /home/abdul_waheed/Music/rv32_for_fyp/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/abdul_waheed/Music/rv32_for_fyp/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem {
  /home/abdul_waheed/Music/rv32_for_fyp/Script/build/ICACHE.mem
  /home/abdul_waheed/Music/rv32_for_fyp/Script/build/DCACHE.mem
}
read_verilog -library xil_defaultlib -sv {
  /home/abdul_waheed/Music/rv32_for_fyp/Config.sv
  /home/abdul_waheed/Music/rv32_for_fyp/Datapath/ALU.sv
  /home/abdul_waheed/Music/rv32_for_fyp/Controller/CPU.sv
  /home/abdul_waheed/Music/rv32_for_fyp/Gemm/Controller/Load_Ex_controller.sv
  /home/abdul_waheed/Music/rv32_for_fyp/Datapath/PC_flip.sv
  /home/abdul_waheed/Music/rv32_for_fyp/Gemm/Controller/Store_Controller.sv
  /home/abdul_waheed/Music/rv32_for_fyp/Gemm/Datapath/accumulator.sv
  /home/abdul_waheed/Music/rv32_for_fyp/Gemm/Datapath/acum_buffer.sv
  /home/abdul_waheed/Music/rv32_for_fyp/Datapath/adder.sv
  /home/abdul_waheed/Music/rv32_for_fyp/Datapath/branch_con.sv
  /home/abdul_waheed/Music/rv32_for_fyp/Gemm/Utilities/buffer.sv
  /home/abdul_waheed/Music/rv32_for_fyp/Gemm/Controller/buffer_accum_ctrl.sv
  /home/abdul_waheed/Music/rv32_for_fyp/Datapath/cva6_csr_unit.sv
  /home/abdul_waheed/Music/rv32_for_fyp/Datapath/extend.sv
  /home/abdul_waheed/Music/rv32_for_fyp/Controller/flip_CU.sv
  /home/abdul_waheed/Music/rv32_for_fyp/Datapath/flip_flop.sv
  /home/abdul_waheed/Music/rv32_for_fyp/gemm.sv
  /home/abdul_waheed/Music/rv32_for_fyp/Gemm/Datapath/gemm_datapath.sv
  /home/abdul_waheed/Music/rv32_for_fyp/Gemm/Datapath/gemm_decoder.sv
  /home/abdul_waheed/Music/rv32_for_fyp/Datapath/hazard_unit.sv
  /home/abdul_waheed/Music/rv32_for_fyp/Datapath/inst_mem.sv
  /home/abdul_waheed/Music/rv32_for_fyp/Gemm/Datapath/mac.sv
  /home/abdul_waheed/Music/rv32_for_fyp/Datapath/main_csr_pipe.sv
  /home/abdul_waheed/Music/rv32_for_fyp/Datapath/mem_unit.sv
  /home/abdul_waheed/Music/rv32_for_fyp/Gemm/Datapath/memory.sv
  /home/abdul_waheed/Music/rv32_for_fyp/Gemm/Datapath/memory_mapped.sv
  /home/abdul_waheed/Music/rv32_for_fyp/Datapath/mux_2x1.sv
  /home/abdul_waheed/Music/rv32_for_fyp/Datapath/mux_4x1.sv
  /home/abdul_waheed/Music/rv32_for_fyp/Gemm/Utilities/muxes.sv
  /home/abdul_waheed/Music/rv32_for_fyp/Gemm/Datapath/pipeline_gen.sv
  /home/abdul_waheed/Music/rv32_for_fyp/Datapath/reg_file.sv
  /home/abdul_waheed/Music/rv32_for_fyp/Gemm/Datapath/super_sys.sv
  /home/abdul_waheed/Music/rv32_for_fyp/Gemm/Datapath/systolic.sv
  /home/abdul_waheed/Music/rv32_for_fyp/Gemm/Datapath/systolic_setup.sv
  /home/abdul_waheed/Music/rv32_for_fyp/Gemm/Datapath/systolic_setup_reverse.sv
  /home/abdul_waheed/Music/rv32_for_fyp/Datapath/x7segb8.sv
  /home/abdul_waheed/Music/rv32_for_fyp/top.sv
  /home/abdul_waheed/Music/rv32_for_fyp/Datapath/mem_data.sv
  /home/abdul_waheed/Music/rv32_for_fyp/Datapath/main_mem.sv
  /home/abdul_waheed/Music/rv32_for_fyp/Datapath/BitCounter.sv
  /home/abdul_waheed/Music/rv32_for_fyp/Gemm/Datapath/Memory_test.sv
  /home/abdul_waheed/Music/rv32_for_fyp/Gemm/Datapath/memory_tb.sv
  /home/abdul_waheed/Music/rv32_for_fyp/soc.sv
  /home/abdul_waheed/Music/rv32_for_fyp/tff.sv
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/abdul_waheed/Music/FYP/Vivado/Nexys-A7-100T-Master.xdc
set_property used_in_implementation false [get_files /home/abdul_waheed/Music/FYP/Vivado/Nexys-A7-100T-Master.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top soc -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef soc.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file soc_utilization_synth.rpt -pb soc_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
