#*****************************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# project.tcl: Tcl script for re-creating project 'project_3'
#
# Generated by Vivado on Sun Sep 22 00:05:50 PKT 2024
# IP Build 2700528 on Thu Nov  7 00:09:20 MST 2019
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (project.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    <none>
#
# 3. The following remote source files that were added to the original project:-
#
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/Gemm/Datapath/systolic_setup.sv"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/Config.sv"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/Gemm/Datapath/acum_buffer.sv"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/Gemm/Datapath/gemm_decoder.sv"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/Gemm/Datapath/accumulator.sv"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/Gemm/Utilities/buffer.sv"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/Gemm/Controller/Store_Controller.sv"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/Gemm/Controller/Load_Ex_controller.sv"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/Gemm/Datapath/systolic.sv"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/Gemm/Datapath/systolic_setup_reverse.sv"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/Gemm/Controller/buffer_accum_ctrl.sv"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/Gemm/Datapath/memory_mapped.sv"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/Gemm/Datapath/mac.sv"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/Gemm/Datapath/memory.sv"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/Gemm/Datapath/gemm_datapath.sv"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/Gemm/Datapath/super_sys.sv"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/Gemm/Utilities/muxes.sv"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/Gemm/Datapath/pipeline_gen.sv"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/gemm.sv"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/soc.sv"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/Core/Datapath/reg_file.sv"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/Core/Datapath/mux_4x1.sv"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/Core/Datapath/ALU.sv"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/Core/Datapath/inst_mem.sv"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/Core/Datapath/mux_2x1.sv"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/Core/Datapath/x7segb8.sv"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/Core/Datapath/flip_flop.sv"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/Core/Datapath/branch_con.sv"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/Core/Datapath/PC_flip.sv"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/Core/Datapath/adder.sv"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/Core/Datapath/cva6_csr_unit.sv"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/Core/Datapath/hazard_unit.sv"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/Core/Datapath/riscv_core.sv"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/Core/Datapath/mem_unit.sv"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/Core/Datapath/extend.sv"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/Core/Controller/pipelined_control.sv"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/Core/Controller/control.sv"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/top.sv"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/clk_divider.sv"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/Gemm/Datapath/banked_memory.sv"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/Gemm/Datapath/bank.sv"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/Script/build/ICACHE.mem"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/Script/build/memory5.mem"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/Script/build/memory8.mem"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/Script/build/memory7.mem"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/Script/build/memory11.mem"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/Script/build/memory14.mem"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/Script/build/memory2.mem"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/Script/build/memory0.mem"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/Script/build/memory4.mem"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/Script/build/memory15.mem"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/Script/build/memory10.mem"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/Script/build/memory13.mem"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/Script/build/memory12.mem"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/Script/build/memory6.mem"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/Script/build/memory9.mem"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/Script/build/memory3.mem"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/Script/build/memory1.mem"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/uart/pcore_csr_defs.svh"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/uart/uart.sv"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/uart/pcore_config_defs.svh"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/uart/uart_rx.sv"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/uart/uart_tx.sv"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/uart/cache_defs.svh"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/uart/mmu_defs.svh"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/uart/pcore_interface_defs.svh"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/uart/ddr_defs.svh"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/uart/c_ext_defs.svh"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/uart/a_ext_defs.svh"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/uart/spi_defs.svh"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/uart/m_ext_defs.svh"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/uart/plic_defs.svh"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/uart/uart_defs.svh"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/Core/Datapath/m_unit.sv"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/Core/Datapath/div_try.sv"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/rtl/Core/Datapath/reg_int.mem"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/fpga/Nexys-A7-100T-Master.xdc"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/fpga/abdul_top_behav.wcfg"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/fpga/copy_riscv_core_tb_func_imp.wcfg"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/fpga/riscv_core_tb_func_impl.wcfg"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/fpga/uart_look.wcfg"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/testbench/tb_random_gemm.sv"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/testbench/memory_tb.sv"
#    "/home/rehan/Downloads/data/Optimizing-RISC-V-for-High-Performance-Matrix-Multiplication-with-Custom-GEMM-Accelerator/testbench/tb_top.sv"
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir [file dirname [info script]]
# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "vivado_project"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "project.tcl"

# Help information for this script
proc print_help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { print_help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/project_3"]"

# Create project
create_project ${_xil_proj_name_} $origin_dir/${_xil_proj_name_} -part xc7a100tcsg324-1
# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [current_project]
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "part" -value "xc7a100tcsg324-1" -objects $obj
set_property -name "platform.description" -value "Vivado generated DSA" -objects $obj
set_property -name "platform.uses_pr" -value "1" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "source_mgmt_mode" -value "DisplayOnly" -objects $obj
set_property -name "webtalk.xsim_launch_sim" -value "190" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/rtl/Gemm/Datapath/systolic_setup.sv"] \
 [file normalize "${origin_dir}/Config.sv"] \
 [file normalize "${origin_dir}/rtl/Gemm/Datapath/acum_buffer.sv"] \
 [file normalize "${origin_dir}/rtl/Gemm/Datapath/gemm_decoder.sv"] \
 [file normalize "${origin_dir}/rtl/Gemm/Datapath/accumulator.sv"] \
 [file normalize "${origin_dir}/rtl/Gemm/Utilities/buffer.sv"] \
 [file normalize "${origin_dir}/rtl/Gemm/Controller/Store_Controller.sv"] \
 [file normalize "${origin_dir}/rtl/Gemm/Controller/Load_Ex_controller.sv"] \
 [file normalize "${origin_dir}/rtl/Gemm/Datapath/systolic.sv"] \
 [file normalize "${origin_dir}/rtl/Gemm/Datapath/systolic_setup_reverse.sv"] \
 [file normalize "${origin_dir}/rtl/Gemm/Controller/buffer_accum_ctrl.sv"] \
 [file normalize "${origin_dir}/rtl/Gemm/Datapath/memory_mapped.sv"] \
 [file normalize "${origin_dir}/rtl/Gemm/Datapath/mac.sv"] \
 [file normalize "${origin_dir}/rtl/Gemm/Datapath/memory.sv"] \
 [file normalize "${origin_dir}/rtl/Gemm/Datapath/gemm_datapath.sv"] \
 [file normalize "${origin_dir}/rtl/Gemm/Datapath/super_sys.sv"] \
 [file normalize "${origin_dir}/rtl/Gemm/Utilities/muxes.sv"] \
 [file normalize "${origin_dir}/rtl/Gemm/Datapath/pipeline_gen.sv"] \
 [file normalize "${origin_dir}/gemm.sv"] \
 [file normalize "${origin_dir}/soc.sv"] \
 [file normalize "${origin_dir}/rtl/Core/Datapath/reg_file.sv"] \
 [file normalize "${origin_dir}/rtl/Core/Datapath/mux_4x1.sv"] \
 [file normalize "${origin_dir}/rtl/Core/Datapath/ALU.sv"] \
 [file normalize "${origin_dir}/rtl/Core/Datapath/inst_mem.sv"] \
 [file normalize "${origin_dir}/rtl/Core/Datapath/mux_2x1.sv"] \
 [file normalize "${origin_dir}/rtl/Core/Datapath/x7segb8.sv"] \
 [file normalize "${origin_dir}/rtl/Core/Datapath/flip_flop.sv"] \
 [file normalize "${origin_dir}/rtl/Core/Datapath/branch_con.sv"] \
 [file normalize "${origin_dir}/rtl/Core/Datapath/PC_flip.sv"] \
 [file normalize "${origin_dir}/rtl/Core/Datapath/adder.sv"] \
 [file normalize "${origin_dir}/rtl/Core/Datapath/cva6_csr_unit.sv"] \
 [file normalize "${origin_dir}/rtl/Core/Datapath/hazard_unit.sv"] \
 [file normalize "${origin_dir}/rtl/Core/Datapath/riscv_core.sv"] \
 [file normalize "${origin_dir}/rtl/Core/Datapath/mem_unit.sv"] \
 [file normalize "${origin_dir}/rtl/Core/Datapath/extend.sv"] \
 [file normalize "${origin_dir}/rtl/Core/Controller/pipelined_control.sv"] \
 [file normalize "${origin_dir}/rtl/Core/Controller/control.sv"] \
 [file normalize "${origin_dir}/top.sv"] \
 [file normalize "${origin_dir}/clk_divider.sv"] \
 [file normalize "${origin_dir}/rtl/Gemm/Datapath/banked_memory.sv"] \
 [file normalize "${origin_dir}/rtl/Gemm/Datapath/bank.sv"] \
 [file normalize "${origin_dir}/Script/build/ICACHE.mem"] \
 [file normalize "${origin_dir}/Script/build/memory5.mem"] \
 [file normalize "${origin_dir}/Script/build/memory8.mem"] \
 [file normalize "${origin_dir}/Script/build/memory7.mem"] \
 [file normalize "${origin_dir}/Script/build/memory11.mem"] \
 [file normalize "${origin_dir}/Script/build/memory14.mem"] \
 [file normalize "${origin_dir}/Script/build/memory2.mem"] \
 [file normalize "${origin_dir}/Script/build/memory0.mem"] \
 [file normalize "${origin_dir}/Script/build/memory4.mem"] \
 [file normalize "${origin_dir}/Script/build/memory15.mem"] \
 [file normalize "${origin_dir}/Script/build/memory10.mem"] \
 [file normalize "${origin_dir}/Script/build/memory13.mem"] \
 [file normalize "${origin_dir}/Script/build/memory12.mem"] \
 [file normalize "${origin_dir}/Script/build/memory6.mem"] \
 [file normalize "${origin_dir}/Script/build/memory9.mem"] \
 [file normalize "${origin_dir}/Script/build/memory3.mem"] \
 [file normalize "${origin_dir}/Script/build/memory1.mem"] \
 [file normalize "${origin_dir}/rtl/uart/pcore_csr_defs.svh"] \
 [file normalize "${origin_dir}/rtl/uart/uart.sv"] \
 [file normalize "${origin_dir}/rtl/uart/pcore_config_defs.svh"] \
 [file normalize "${origin_dir}/rtl/uart/uart_rx.sv"] \
 [file normalize "${origin_dir}/rtl/uart/uart_tx.sv"] \
 [file normalize "${origin_dir}/rtl/uart/cache_defs.svh"] \
 [file normalize "${origin_dir}/rtl/uart/mmu_defs.svh"] \
 [file normalize "${origin_dir}/rtl/uart/pcore_interface_defs.svh"] \
 [file normalize "${origin_dir}/rtl/uart/ddr_defs.svh"] \
 [file normalize "${origin_dir}/rtl/uart/c_ext_defs.svh"] \
 [file normalize "${origin_dir}/rtl/uart/a_ext_defs.svh"] \
 [file normalize "${origin_dir}/rtl/uart/spi_defs.svh"] \
 [file normalize "${origin_dir}/rtl/uart/m_ext_defs.svh"] \
 [file normalize "${origin_dir}/rtl/uart/plic_defs.svh"] \
 [file normalize "${origin_dir}/rtl/uart/uart_defs.svh"] \
 [file normalize "${origin_dir}/rtl/Core/Datapath/m_unit.sv"] \
 [file normalize "${origin_dir}/rtl/Core/Datapath/div_try.sv"] \
 [file normalize "${origin_dir}/rtl/Core/Datapath/reg_int.mem"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/rtl/Gemm/Datapath/systolic_setup.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/Config.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/Gemm/Datapath/acum_buffer.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/Gemm/Datapath/gemm_decoder.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/Gemm/Datapath/accumulator.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/Gemm/Utilities/buffer.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/Gemm/Controller/Store_Controller.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/Gemm/Controller/Load_Ex_controller.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/Gemm/Datapath/systolic.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/Gemm/Datapath/systolic_setup_reverse.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/Gemm/Controller/buffer_accum_ctrl.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/Gemm/Datapath/memory_mapped.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/Gemm/Datapath/mac.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/Gemm/Datapath/memory.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/Gemm/Datapath/gemm_datapath.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/Gemm/Datapath/super_sys.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/Gemm/Utilities/muxes.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/Gemm/Datapath/pipeline_gen.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/gemm.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/soc.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/Core/Datapath/reg_file.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/Core/Datapath/mux_4x1.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/Core/Datapath/ALU.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/Core/Datapath/inst_mem.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/Core/Datapath/mux_2x1.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/Core/Datapath/x7segb8.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/Core/Datapath/flip_flop.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/Core/Datapath/branch_con.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/Core/Datapath/PC_flip.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/Core/Datapath/adder.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/Core/Datapath/cva6_csr_unit.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/Core/Datapath/hazard_unit.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/Core/Datapath/riscv_core.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/Core/Datapath/mem_unit.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/Core/Datapath/extend.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/Core/Controller/pipelined_control.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/Core/Controller/control.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/top.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/clk_divider.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/Gemm/Datapath/banked_memory.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/Gemm/Datapath/bank.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/Script/build/ICACHE.mem"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Memory File" -objects $file_obj

set file "$origin_dir/Script/build/memory5.mem"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Memory File" -objects $file_obj

set file "$origin_dir/Script/build/memory8.mem"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Memory File" -objects $file_obj

set file "$origin_dir/Script/build/memory7.mem"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Memory File" -objects $file_obj

set file "$origin_dir/Script/build/memory11.mem"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Memory File" -objects $file_obj

set file "$origin_dir/Script/build/memory14.mem"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Memory File" -objects $file_obj

set file "$origin_dir/Script/build/memory2.mem"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Memory File" -objects $file_obj

set file "$origin_dir/Script/build/memory0.mem"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Memory File" -objects $file_obj

set file "$origin_dir/Script/build/memory4.mem"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Memory File" -objects $file_obj

set file "$origin_dir/Script/build/memory15.mem"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Memory File" -objects $file_obj

set file "$origin_dir/Script/build/memory10.mem"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Memory File" -objects $file_obj

set file "$origin_dir/Script/build/memory13.mem"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Memory File" -objects $file_obj

set file "$origin_dir/Script/build/memory12.mem"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Memory File" -objects $file_obj

set file "$origin_dir/Script/build/memory6.mem"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Memory File" -objects $file_obj

set file "$origin_dir/Script/build/memory9.mem"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Memory File" -objects $file_obj

set file "$origin_dir/Script/build/memory3.mem"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Memory File" -objects $file_obj

set file "$origin_dir/Script/build/memory1.mem"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Memory File" -objects $file_obj

set file "$origin_dir/rtl/uart/pcore_csr_defs.svh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "$origin_dir/rtl/uart/uart.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/uart/pcore_config_defs.svh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "$origin_dir/rtl/uart/uart_rx.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/uart/uart_tx.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/uart/cache_defs.svh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "$origin_dir/rtl/uart/mmu_defs.svh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "$origin_dir/rtl/uart/pcore_interface_defs.svh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "$origin_dir/rtl/uart/ddr_defs.svh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "$origin_dir/rtl/uart/c_ext_defs.svh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "$origin_dir/rtl/uart/a_ext_defs.svh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "$origin_dir/rtl/uart/spi_defs.svh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "$origin_dir/rtl/uart/m_ext_defs.svh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "$origin_dir/rtl/uart/plic_defs.svh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "$origin_dir/rtl/uart/uart_defs.svh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "$origin_dir/rtl/Core/Datapath/m_unit.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/Core/Datapath/div_try.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/Core/Datapath/reg_int.mem"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Memory File" -objects $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "top" -value "soc" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/fpga/Nexys-A7-100T-Master.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/fpga/Nexys-A7-100T-Master.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property -name "target_constrs_file" -value "[file normalize "$origin_dir/fpga/Nexys-A7-100T-Master.xdc"]" -objects $obj
set_property -name "target_part" -value "xc7a100tcsg324-1" -objects $obj
set_property -name "target_ucf" -value "[file normalize "$origin_dir/fpga/Nexys-A7-100T-Master.xdc"]" -objects $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
set files [list \
 [file normalize "${origin_dir}/fpga/abdul_top_behav.wcfg"] \
 [file normalize "${origin_dir}/fpga/copy_riscv_core_tb_func_imp.wcfg"] \
 [file normalize "${origin_dir}/fpga/riscv_core_tb_func_impl.wcfg"] \
 [file normalize "${origin_dir}/fpga/uart_look.wcfg"] \
 [file normalize "${origin_dir}/testbench/tb_random_gemm.sv"] \
 [file normalize "${origin_dir}/testbench/memory_tb.sv"] \
 [file normalize "${origin_dir}/testbench/tb_top.sv"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sim_1' fileset file properties for remote files
set file "$origin_dir/testbench/tb_random_gemm.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/testbench/memory_tb.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/testbench/tb_top.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj


# Set 'sim_1' fileset file properties for local files
# None

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "top" -value "tb_random_gemm" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj

# Set 'utils_1' fileset object
set obj [get_filesets utils_1]
# Empty (no sources present)

# Set 'utils_1' fileset properties
set obj [get_filesets utils_1]

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xc7a100tcsg324-1 -flow {Vivado Synthesis 2019} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2019" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_1]
set_property -name "part" -value "xc7a100tcsg324-1" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xc7a100tcsg324-1 -flow {Vivado Implementation 2019} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2019" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {
set_property -name "options.verbose" -value "1" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
set obj [get_runs impl_1]
set_property -name "part" -value "xc7a100tcsg324-1" -objects $obj
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.phys_opt_design.is_enabled" -value "1" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:${_xil_proj_name_}"
# Create 'drc_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "drc_1" ] ] ""]} {
create_dashboard_gadget -name {drc_1} -type drc
}
set obj [get_dashboard_gadgets [ list "drc_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_drc_0" -objects $obj

# Create 'methodology_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "methodology_1" ] ] ""]} {
create_dashboard_gadget -name {methodology_1} -type methodology
}
set obj [get_dashboard_gadgets [ list "methodology_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_methodology_0" -objects $obj

# Create 'power_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "power_1" ] ] ""]} {
create_dashboard_gadget -name {power_1} -type power
}
set obj [get_dashboard_gadgets [ list "power_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_power_0" -objects $obj

# Create 'timing_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "timing_1" ] ] ""]} {
create_dashboard_gadget -name {timing_1} -type timing
}
set obj [get_dashboard_gadgets [ list "timing_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_timing_summary_0" -objects $obj

# Create 'utilization_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_1" ] ] ""]} {
create_dashboard_gadget -name {utilization_1} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_1" ] ]
set_property -name "reports" -value "synth_1#synth_1_synth_report_utilization_0" -objects $obj
set_property -name "run.step" -value "synth_design" -objects $obj
set_property -name "run.type" -value "synthesis" -objects $obj

# Create 'utilization_2' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_2" ] ] ""]} {
create_dashboard_gadget -name {utilization_2} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_2" ] ]
set_property -name "reports" -value "impl_1#impl_1_place_report_utilization_0" -objects $obj

move_dashboard_gadget -name {utilization_1} -row 0 -col 0
move_dashboard_gadget -name {power_1} -row 1 -col 0
move_dashboard_gadget -name {drc_1} -row 2 -col 0
move_dashboard_gadget -name {timing_1} -row 0 -col 1
move_dashboard_gadget -name {utilization_2} -row 1 -col 1
move_dashboard_gadget -name {methodology_1} -row 2 -col 1
